[package]
name = "morphoid"
version = "0.1.0"
authors = ["Kirill Lastovirya <kirill.lastovirya@gmail.com>"]

[dependencies]
actix-web = "0.7"
itertools = "0.8.0"
lazy_static = "1.2.0"
time = "*"
rand = "0.6"