[package]
name = "rust-morphoid"
version = "0.1.0"
authors = ["Kirill Lastovirya <kirill.lastovirya@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6"
env_logger = "0.11"

api = { path = "./api" }

[workspace]
members = [
    "morphoid",
    "api"
]

[[bin]]
name = "morphoid"
path = "bin/main.rs"
