[package]
name = "morphoid"
version = "0.1.0"
authors = ["Kirill Lastovirya <kirill.lastovirya@gmail.com>"]
build = "build.rs"

[dependencies]
itertools = "0.8.0"
lazy_static = "1.3.0"
time = "*"
rand = "0.6.5"

actix-web = "0.7.19"
futures = "0.1"
env_logger = "*"
json = "0.11.13"

#rollbar = "0.5.1"
