version: 2

jobs:
  build:
    docker:
      # The image used to build our project, build
      # your own using the Dockerfile provided below
      # and replace here. I put my own image here for
      # the example.
      - image: kirhgoff/rust-npm-circleci:latest

    environment:
      TZ: "/usr/share/zoneinfo/Australia/melbourne"

    steps:
      - checkout
      - restore_cache:
          key: project-cache
#      - run:
#          name: Run webpack
#          command: |
#            cd ui
#            npm install
      - run:
          name: Nightly Build
          command: |
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            rustup run nightly cargo build

      - run:
          name: Test
          command: rustup run nightly cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
            - "./ui/node_modules"
